<?php

    return [
        [ 
            'Pizza Pellegrino',
            'Mexican Burritos',
            'Chinese Restaurant',
            'Da Ciro',
            'Instanbul Kebab',
            'Orlando Bakery',
            'Pizzeria SanMarco',
            'Osteria Giovanni',
            'Superlux Restaurant',
            'SushiBar',

            'Apelle',
            'Braceria La Romantica',
            'America Graffiti',
            'Chocolat',
            'Nonno Umberto',
            'Gelateria La Romana',
            'Gelateria Degli Angeli',
            'Sushi Tokyo',
            'Agapimu',
            'Mesopotamia Kebab',
            'The Lab',
            'Osteria Del Ghetto',
            'Piedra Del Sol',
            'Sapori Solari',
            'Fud Bottega Sicula',
            'Piadina La Romagnola',
            'Patata Regina',
            'Punto Veg',
            'Zazie',
            'La Trattoria Vegetariana',
            'Pasticceria Vegana',
            'Ali Babà Kebab',
            'Kebabis',
            'Le Nuvole',
            'I Piaceri Di Lucrezia',
            'Bonelli Burgers',
            'Wasabi',
            'Pizzeria Dall\'Ospite',
            'Trattoria La Gatta',
            'Il Mandolino',
            'Toffee Art Cafe',
            'Il Piccolo Cowboy',
            'Papparè',
            'La Bella Napoli',
            'Dai Ragazzi Ristorante Pizzeria',
            'Bella Rosa',
            'Shangai',
            'Il Drago D\'Oro',
            'Hamburgeria Via Adelardi',
            'Pasticceria Pivati'
        ],
        [
            'pizzapellegrino@mail.it',
            'mexicanburritos@mail.it',
            'chineserestaurant@mail.it',
            'daciro@mail.it',
            'instanbulkebab@mail.it',
            'orlandobakery@mail.it',
            'pizzeriasanmarco@mail.it',
            'osteriagiovanni@mail.it',
            'superluxrestaurant@mail.it',
            'sushibar@mail.it',

            'apelle@mail.it',
            'bracerialaromantica@mail.it',
            'americagraffiti@mail.it',
            'chocolat@mail.it',
            'nonnoumberto@mail.it',
            'gelaterialaromana@mail.it',
            'gelateriadegliangeli@mail.it',
            'sushitokyo@mail.it',
            'agapimu@mail.it',
            'mesopotamiakebab@mail.it',
            'thelab@mail.it',
            'osteriadelghetto@mail.it',
            'piedradelsol@mail.it',
            'saporisolari@mail.it',
            'fudbottegasicula@mail.it',
            'piadinalaromagnola@mail.it',
            'patataregina@mail.it',
            'puntoveg@mail.it',
            'zazie@mail.it',
            'latrattoriavegetariana@mail.it',
            'pasticceriavegana@mail.it',
            'alibabakebab@mail.it',
            'kebabis@mail.it',
            'lenuvole@mail.it',
            'ipiaceridilucrezia@mail.it',
            'bonelliburgers@mail.it',
            'wasabi@mail.it',
            'pizzeriadallospite@mail.it',
            'trattorialagatta@mail.it',
            'ilmandolino@mail.it',
            'toffeeartcafe@mail.it',
            'ilpiccolocowboy@mail.it',
            'pappare@mail.it',
            'labellanapoli@mail.it',
            'dairagazziristorantepizzeria@mail.it',
            'bellarosa@mail.it',
            'shangai@mail.it',
            'ildragodoro@mail.it',
            'hamburgeriaviaadelardi@mail.it',
            'pasticceriapivati@mail.it'
        ],
        [
            'pizzapellegrino',
            'mexicanburritos',
            'chineserestaurant',
            'daciro',
            'instanbulkebab',
            'orlandobaker',
            'pizzeriasanmarco',
            'osteriagiovanni',
            'superluxrestaurant',
            'sushibar',

            'apelle',
            'bracerialaromantica',
            'americagraffiti',
            'chocolat',
            'nonnoumberto',
            'gelaterialaromana',
            'gelateriadegliangeli',
            'sushitokyo',
            'agapimu',
            'mesopotamiakebab',
            'thelab',
            'osteriadelghetto',
            'piedradelsol',
            'saporisolari',
            'fudbottegasicula',
            'piadinalaromagnola',
            'patataregina',
            'puntoveg',
            'zazie',
            'latrattoriavegetariana',
            'pasticceriavegana',
            'alibabakebab',
            'kebabis',
            'lenuvole',
            'ipiaceridilucrezia',
            'bonelliburgers',
            'wasabi',
            'pizzeriadallospite',
            'trattorialagatta',
            'ilmandolino',
            'toffeeartcafe',
            'ilpiccolocowboy',
            'pappare',
            'labellanapoli',
            'dairagazziristorantepizzeria',
            'bellarosa',
            'shangai',
            'ildragodoro',
            'hamburgeriaviaadelardi',
            'pasticceriapivati'
        ],
        [
            'via Roma, 18',
            'via Galileo Galilei, 113',
            'piazza Centrale, 3',
            'via Ai Poggi, 25',
            'via Anna Frank, 57',
            'via Dei Caduti, 10',
            'via Copernico, 33',
            'via Giorgio Jan, 40',
            'via Francesco Redi, 1',
            'via Felice Bellotti, 54',

            'via Roma, 21',
            'via Galileo Galilei, 13',
            'piazza Centrale, 8',
            'via Ai Poggi, 55',
            'via Anna Frank, 2',
            'via Dei Caduti, 98',
            'via Copernico, 124',
            'via Giorgio Jan, 1',
            'via Francesco Redi, 88',
            'via Felice Bellotti, 62',
            'via Roma, 11',
            'via Galileo Galilei, 19',
            'piazza Centrale, 21',
            'via Ai Poggi, 4',
            'via Anna Frank, 9',
            'via Dei Caduti, 90',
            'via Copernico, 50',
            'via Giorgio Jan, 20',
            'via Francesco Redi, 12',
            'via Felice Bellotti, 7',
            'via Roma, 60',
            'via Galileo Galilei, 3',
            'piazza Centrale, 15',
            'via Ai Poggi, 16',
            'via Anna Frank, 17',
            'via Dei Caduti, 18',
            'via Copernico, 26',
            'via Giorgio Jan, 27',
            'via Francesco Redi, 28',
            'via Felice Bellotti, 31',
            'via Roma, 11',
            'via Galileo Galilei, 32',
            'piazza Centrale, 11',
            'via Ai Poggi, 43',
            'via Anna Frank, 45',
            'via Dei Caduti, 65',
            'via Copernico, 76',
            'via Giorgio Jan, 54',
            'via Francesco Redi, 21',
            'via Felice Bellotti, 91'
        ],
        [
            '12345678910',
            '12345678911',
            '12345678912',
            '12345678913',
            '12345678914',
            '12345678915',
            '12345678916',
            '12345678917',
            '12345678918',
            '12345678919',

            '12345678920',
            '12345678921',
            '12345678922',
            '12345678923',
            '12345678924',
            '12345678925',
            '12345678926',
            '12345678927',
            '12345678928',
            '12345678929',
            '12345678930',
            '12345678931',
            '12345678932',
            '12345678933',
            '12345678934',
            '12345678935',
            '12345678936',
            '12345678937',
            '12345678938',
            '12345678939',
            '12345678940',
            '12345678941',
            '12345678942',
            '12345678943',
            '12345678944',
            '12345678945',
            '12345678946',
            '12345678947',
            '12345678948',
            '12345678949',
            '12345678950',
            '12345678951',
            '12345678952',
            '12345678953',
            '12345678954',
            '12345678955',
            '12345678956',
            '12345678957',
            '12345678958',
            '12345678959',
        ],
        [
            'pizza-pellegrino',
            'mexican-burritos',
            'chinese-restaurant',
            'da-ciro',
            'instanbul-kebab',
            'orlando-bakery',
            'pizzeria-sanmarco',
            'osteria-giovanni',
            'superlux-restaurant',
            'sushi-bar',

            'apelle',
            'braceria-la-romantica',
            'america-graffiti',
            'chocolat',
            'nonno-umberto',
            'gelateria-la-romana',
            'gelateria-degli-angeli',
            'sushi-tokyo',
            'agapimu',
            'mesopotamia-kebab',
            'the-lab',
            'osteria-del-ghetto',
            'piedra-del-sol',
            'sapori-solari',
            'fud-bottega-sicula',
            'piadina-la-romagnola',
            'patata-regina',
            'punto-veg',
            'zazie',
            'la-trattoria-vegetariana',
            'pasticceria-vegana',
            'ali-baba-kebab',
            'kebabis',
            'le-nuvole',
            'i-piaceri-di-lucrezia',
            'bonelli-burgers',
            'wasabi',
            'pizzeria-dall-ospite',
            'trattoria-la-gatta',
            'il-mandolino',
            'toffee-art-cafe',
            'il-piccolo-cowboy',
            'pappare',
            'la-bella-napoli',
            'dai-ragazzi-ristorante-pizzeria',
            'bella-rosa',
            'shangai',
            'il-drago-d-oro',
            'hamburgeria-via-adelardi',
            'pasticceria-pivati'
        ]
    ];